package com.vinplay.dal.service.seamless.gsc;

import com.vinplay.vbee.common.config.VBeePath;
import com.vinplay.vbee.common.pools.ConnectionPool;
import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.AfterClass;
import org.junit.Assume;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import javax.servlet.http.HttpServletRequest;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Properties;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

/**
 * Phase 2 POC golden-file contract test for {@link GscBalanceAggregator}.
 *
 * <p>Each fixture pair under
 * {@code src/test/resources/seamless/gsc/balance/NN_request.json} +
 * {@code NN_response.json} is replayed through the aggregator with a
 * stub {@link GscConfigProvider} that uses a known secret
 * ({@code TEST_SECRET}). The aggregator's response is compared to the
 * expected payload as <em>JSON-tree-equivalent</em> — field ordering is
 * tolerated because gson and org.json may emit fields in different
 * orders even though both are byte-equal under value-equivalence.
 *
 * <h2>Fixture sourcing</h2>
 * Production payload shapes were sampled from
 * {@code vinplay.gsc_event_log WHERE gsc_endpoint='balance'} — see the
 * commit message and design doc §3 phase 2. The actual
 * {@code sign} values had to be regenerated against a known test
 * secret because the live operator key is not in the test environment.
 *
 * <h2>Fixtures</h2>
 * <ol>
 *   <li>{@code 01} — KRW, single batch member, user does not exist in DB
 *       → "Member not found" branch.</li>
 *   <li>{@code 02} — VND, single batch member, user does not exist in DB
 *       → exercises the alternate currency path.</li>
 *   <li>{@code 03} — KRW, invalid signature → SIGNATURE_ERROR branch
 *       maps to legacy {@code code=1004 / "Invalid sign"} shape.</li>
 *   <li>{@code 04} — KRW, empty {@code batch_requests} array →
 *       empty-data response, top-level {@code code=0}.</li>
 *   <li>{@code 05} — KRW, real user from the live DB
 *       ({@code users.id=5107}, {@code user_name=botxocxoc131}). The
 *       expected response uses a sentinel {@code "@vin@"} that the test
 *       resolves to the user's current {@code vin} value at run time.</li>
 * </ol>
 *
 * <p>Skips with {@code Assume} when no DB password is supplied — same
 * pattern as {@link com.vinplay.dal.service.seamless.SeamlessWalletAggregatorTest}.
 */
public class GscBalanceAggregatorTest {

    private static final String TEST_SECRET = "TEST_SECRET";
    private static final long TEST_USER_ID = 5107L;
    private static volatile String TEST_USERNAME;
    private static volatile boolean bootstrapSkipped = false;

    private GscBalanceAggregator aggregator;

    @BeforeClass
    public static void bootstrapPool() throws Exception {
        String pw = System.getProperty("test.mysql.password");
        if (pw == null || pw.isEmpty()) pw = System.getenv("MYSQL_PASSWORD");
        if (pw == null || pw.isEmpty()) {
            bootstrapSkipped = true;
            System.out.println("GscBalanceAggregatorTest: password not supplied; tests will be skipped");
            return;
        }

        URL propsUrl = GscBalanceAggregatorTest.class
                .getClassLoader()
                .getResource("config/db_pool.properties");
        String resourcesDir = propsUrl.getPath().replace("config/db_pool.properties", "");
        VBeePath.basePath = resourcesDir;

        Properties props = new Properties();
        try (InputStream is = propsUrl.openStream()) {
            props.load(is);
        }
        final String PLACEHOLDER = "__INJECT_AT_TEST_TIME__";
        if (PLACEHOLDER.equals(props.getProperty("mysqlpoolname.password", ""))) {
            props.setProperty("mysqlpoolname.password", pw);
        }
        java.io.File propsFile = new java.io.File(propsUrl.toURI());
        try (java.io.FileOutputStream fos = new java.io.FileOutputStream(propsFile)) {
            props.store(fos, "Auto-generated by GscBalanceAggregatorTest — password injected at test time");
        }

        ConnectionPool.getInstance();

        // Resolve TEST_USERNAME from the DB so the test does not hard-code
        // seed-specific values. If the row doesn't exist, leave null and
        // the per-test @Before will Assume-skip.
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT user_name FROM vinplay.users WHERE id = ?")) {
            ps.setLong(1, TEST_USER_ID);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) TEST_USERNAME = rs.getString("user_name");
            }
        }
    }

    @AfterClass
    public static void cleanUp() {
        if (bootstrapSkipped) return;
        try {
            URL propsUrl = GscBalanceAggregatorTest.class
                    .getClassLoader()
                    .getResource("config/db_pool.properties");
            if (propsUrl != null) {
                Properties props = new Properties();
                try (InputStream is = propsUrl.openStream()) {
                    props.load(is);
                }
                props.setProperty("mysqlpoolname.password", "__INJECT_AT_TEST_TIME__");
                java.io.File propsFile = new java.io.File(propsUrl.toURI());
                try (java.io.FileOutputStream fos = new java.io.FileOutputStream(propsFile)) {
                    props.store(fos,
                            "Integration-test DB pool — password placeholder restored after run");
                }
            }
        } catch (Exception e) {
            System.err.println("GscBalanceAggregatorTest: could not restore placeholder (non-fatal): "
                    + e.getMessage());
        }
    }

    @Before
    public void setUp() {
        Assume.assumeFalse(
                "test.mysql.password or MYSQL_PASSWORD must be set",
                bootstrapSkipped);
        Assume.assumeNotNull(
                "users.id=" + TEST_USER_ID + " must exist (seed via task #176)",
                TEST_USERNAME);

        aggregator = new GscBalanceAggregator(new GscConfigProvider() {
            @Override public String getSecretKey() { return TEST_SECRET; }
            @Override public double getOperatorExchangeRate() { return 1.0; }
            @Override
            public int getCurrencyExchangeRate(String currencyCode) {
                if (currencyCode == null) return 0;
                String s = currencyCode.trim();
                if ("KRW".equals(s) || "VND".equals(s) || "USD".equals(s) || "CNY".equals(s)
                        || "IDR".equals(s) || "MYR".equals(s) || "JPY".equals(s)
                        || "THB".equals(s) || "SGD".equals(s)) {
                    return 1;
                }
                if ("KRW2".equals(s) || "VND2".equals(s) || "IDR2".equals(s)
                        || "MMK2".equals(s) || "LAK2".equals(s) || "KHR2".equals(s)) {
                    return 1000;
                }
                return 0;
            }
        });
    }

    // ─────────────────────────────────────────────────────────────────
    // Fixtures
    // ─────────────────────────────────────────────────────────────────

    @Test public void fixture01_userNotFound_KRW() throws Exception { runFixture("01"); }
    @Test public void fixture02_userNotFound_VND() throws Exception { runFixture("02"); }
    @Test public void fixture03_invalidSignature() throws Exception { runFixture("03"); }
    @Test public void fixture04_emptyBatchRequests() throws Exception { runFixture("04"); }
    @Test public void fixture05_realUserBalance() throws Exception { runFixture("05"); }

    /**
     * A test exercising the actual production wire shapes from
     * {@code gsc_event_log} (verbatim — sign+request_time as captured).
     * The captured sign won't validate against {@link #TEST_SECRET}, so
     * the aggregator returns the SIGNATURE_ERROR shape regardless of the
     * captured response. Verifies the parser doesn't choke on real
     * payloads.
     */
    @Test
    public void productionPayloadsParseWithoutThrowing() throws Exception {
        String[] payloads = {
                "{\"sign\": \"99d8185c4d7c3939bc9c232fc383b0da\", \"currency\": \"KRW\", \"game_type\": \"\", \"request_time\": \"1777706702\", \"operator_code\": \"G7A1\", \"batch_requests\": [{\"game_type\": \"\", \"product_code\": 1002, \"transactions\": [], \"member_account\": \"khongduong\"}]}",
                "{\"sign\": \"36e5bfd072b758d07a7ceb503d31d505\", \"currency\": \"VND\", \"game_type\": \"\", \"request_time\": \"1777696496\", \"operator_code\": \"G7A1\", \"batch_requests\": [{\"game_type\": \"\", \"product_code\": 1091, \"transactions\": [], \"member_account\": \"sunkrvip999\"}]}",
                "{\"sign\": \"2a676c3c6c7f890f82847a9beb4e5502\", \"currency\": \"KRW\", \"game_type\": \"\", \"request_time\": \"1777705550\", \"operator_code\": \"G7A1\", \"batch_requests\": [{\"game_type\": \"\", \"product_code\": 1002, \"transactions\": [], \"member_account\": \"hayquamnoi\"}]}"
        };
        for (String body : payloads) {
            String resp = aggregator.handle(mockRequest(body));
            assertNotNull(resp);
            JSONObject obj = new JSONObject(resp);
            // Live secret won't match the test secret → SIGNATURE_ERROR
            assertEquals("Invalid sign", obj.optString("message"));
            assertEquals(1004, obj.optInt("code"));
        }
    }

    // ─────────────────────────────────────────────────────────────────
    // Helpers
    // ─────────────────────────────────────────────────────────────────

    private void runFixture(String name) throws Exception {
        String reqPath = "seamless/gsc/balance/" + name + "_request.json";
        String respPath = "seamless/gsc/balance/" + name + "_response.json";
        String reqBody = readResource(reqPath);
        String expectedRaw = readResource(respPath);
        assertNotNull("missing fixture " + reqPath, reqBody);
        assertNotNull("missing fixture " + respPath, expectedRaw);

        JSONObject expected = resolveDynamic(new JSONObject(expectedRaw));

        String actualJson = aggregator.handle(mockRequest(reqBody));
        assertNotNull("aggregator returned null for " + name, actualJson);
        JSONObject actual = new JSONObject(actualJson);

        assertJsonEquals("fixture " + name + ": response mismatch.\n  expected="
                + expected + "\n  actual=" + actual, expected, actual);
    }

    /**
     * Replace dynamic sentinels in fixture {@code _response.json} files
     * with values resolved against the live DB at test time:
     * {@code "@vin@"} → current {@code users.vin} for {@code TEST_USER_ID}.
     */
    private JSONObject resolveDynamic(JSONObject expected) throws Exception {
        if (!expected.optBoolean("_dynamic_balance", false)) return expected;
        long vin = readVin(TEST_USER_ID);

        // Mutate in place: walk to data[].balance and replace "@vin@" with vin.
        expected.remove("_dynamic_balance");
        JSONArray data = expected.optJSONArray("data");
        if (data != null) {
            for (int i = 0; i < data.length(); i++) {
                JSONObject item = data.optJSONObject(i);
                if (item == null) continue;
                Object bal = item.opt("balance");
                if ("@vin@".equals(bal)) {
                    // Aggregator emits balance as a double after Math.round/10000.
                    double balanceD = Math.round((double) vin * 1.0 * 10000.0) / 10000.0;
                    item.put("balance", balanceD);
                }
            }
        }
        return expected;
    }

    private static long readVin(long userId) throws Exception {
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement("SELECT vin FROM vinplay.users WHERE id = ?")) {
            ps.setLong(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) throw new IllegalStateException("user " + userId + " not in DB");
                return rs.getLong(1);
            }
        }
    }

    private static String readResource(String path) throws Exception {
        try (InputStream is = GscBalanceAggregatorTest.class
                .getClassLoader().getResourceAsStream(path)) {
            if (is == null) return null;
            BufferedReader r = new BufferedReader(new InputStreamReader(is, StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder();
            String line;
            while ((line = r.readLine()) != null) sb.append(line).append('\n');
            return sb.toString().trim();
        }
    }

    /**
     * Tree-equivalent JSON comparison. Order-insensitive on object keys,
     * order-sensitive on arrays (matters for {@code data} array shape
     * stability), value-comparing by string form so {@code 0} and
     * {@code 0.0} are NOT considered equal — which is exactly what we
     * want, since the aggregator emits {@code 0.0} from
     * {@code Math.round(...) / 10000.0} matching legacy gson output.
     */
    private static void assertJsonEquals(String msg, Object expected, Object actual) {
        if (expected instanceof JSONObject && actual instanceof JSONObject) {
            JSONObject e = (JSONObject) expected;
            JSONObject a = (JSONObject) actual;
            assertEquals(msg + " (key set)", normalizeKeys(e), normalizeKeys(a));
            for (Iterator<String> it = e.keys(); it.hasNext(); ) {
                String k = it.next();
                assertJsonEquals(msg + "." + k, e.get(k), a.get(k));
            }
            return;
        }
        if (expected instanceof JSONArray && actual instanceof JSONArray) {
            JSONArray e = (JSONArray) expected;
            JSONArray a = (JSONArray) actual;
            assertEquals(msg + " (array length)", e.length(), a.length());
            for (int i = 0; i < e.length(); i++) {
                assertJsonEquals(msg + "[" + i + "]", e.get(i), a.get(i));
            }
            return;
        }
        if (expected instanceof Number && actual instanceof Number) {
            // Compare numerically: 0 vs 0.0 are equal because both serialize
            // to the same legacy field (gson emits balance as a double).
            // Use double precision throughout.
            double ed = ((Number) expected).doubleValue();
            double ad = ((Number) actual).doubleValue();
            assertTrue(msg + " (number) expected=" + ed + " actual=" + ad,
                    Math.abs(ed - ad) < 1e-9);
            return;
        }
        assertEquals(msg, String.valueOf(expected), String.valueOf(actual));
    }

    private static java.util.Set<String> normalizeKeys(JSONObject o) {
        java.util.TreeSet<String> set = new java.util.TreeSet<>();
        for (Iterator<String> it = o.keys(); it.hasNext(); ) set.add(it.next());
        return set;
    }

    /** HttpServletRequest dynamic-proxy returning the body via getReader. */
    private static HttpServletRequest mockRequest(final String body) {
        return (HttpServletRequest) Proxy.newProxyInstance(
                HttpServletRequest.class.getClassLoader(),
                new Class<?>[]{HttpServletRequest.class},
                new InvocationHandler() {
                    @Override
                    public Object invoke(Object p, Method m, Object[] a) throws Throwable {
                        if ("getReader".equals(m.getName())) {
                            return new BufferedReader(new InputStreamReader(
                                    new ByteArrayInputStream(body.getBytes(StandardCharsets.UTF_8)),
                                    StandardCharsets.UTF_8));
                        }
                        if ("getHeaderNames".equals(m.getName())) {
                            return java.util.Collections.enumeration(java.util.Collections.<String>emptyList());
                        }
                        Class<?> ret = m.getReturnType();
                        if (ret == boolean.class) return Boolean.FALSE;
                        if (ret == int.class) return Integer.valueOf(0);
                        if (ret == long.class) return Long.valueOf(0L);
                        if (ret == void.class) return null;
                        if (ret.isPrimitive()) return Integer.valueOf(0);
                        return null;
                    }
                });
    }

    // Suppress "unused" warning for LinkedHashMap import (used in shape comments).
    @SuppressWarnings("unused")
    private static Map<String, Object> _unused() { return new LinkedHashMap<>(); }
}
