package com.vinplay.dal.dao.impl;

import com.vinplay.dal.dao.TopRechargeMoneyDAO;
import com.vinplay.vbee.common.config.VBeePath;
import com.vinplay.vbee.common.pools.ConnectionPool;
import com.vinplay.vbee.common.response.TopRechargeMoneyResponse;
import org.junit.AfterClass;
import org.junit.Assume;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import java.util.Properties;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

/**
 * SUN-13xx Phase 7 — wallet unification.
 *
 * <p>Verifies the recharge-ranking + user-index queries now read deposit totals
 * from the {@code v_derived_deposit_total} view (sourced from money_transaction)
 * instead of the dropped {@code users.recharge_money} column.
 *
 * <p>Inserts one DEPOSIT_BANK row into the money ledger for a known test user,
 * then asserts the user appears at rank #1 in the TopRechargeMoney result with
 * the correct deposit_total.
 *
 * <p><b>Prerequisite:</b> sunwinkr-mysql container running on 127.0.0.1:3306
 * with Phase 0 + Phase 7 view migrations applied. User 5107 must have a
 * {@code PLAYER_VIN} money_account.
 *
 * <p>Password injection mirrors {@link com.vinplay.dal.service.MoneyGatewayDualWriteTest}
 * — via {@code -Dtest.mysql.password=...} or {@code MYSQL_PASSWORD} env var.
 * Tests {@link Assume}-skip when neither is set.
 */
public class DerivedViewBackedReportTest {

    private static final String REF_PREFIX = "test_derived_view_";
    private static final long TEST_DEPOSIT_AMOUNT = 1_234_567L;

    private static volatile boolean bootstrapSkipped = false;
    private static volatile long testUserId = -1L;
    private static volatile String testNickname = null;

    @BeforeClass
    public static void bootstrapPool() throws Exception {
        String pw = System.getProperty("test.mysql.password");
        if (pw == null || pw.isEmpty()) {
            pw = System.getenv("MYSQL_PASSWORD");
        }
        if (pw == null || pw.isEmpty()) {
            bootstrapSkipped = true;
            System.out.println("DerivedViewBackedReportTest: password not supplied; tests will be skipped");
            return;
        }

        URL propsUrl = DerivedViewBackedReportTest.class
                .getClassLoader()
                .getResource("config/db_pool.properties");
        if (propsUrl == null) {
            bootstrapSkipped = true;
            System.out.println("DerivedViewBackedReportTest: db_pool.properties not on classpath; skipping");
            return;
        }
        String resourcesDir = propsUrl.getPath().replace("config/db_pool.properties", "");
        VBeePath.basePath = resourcesDir;

        Properties props = new Properties();
        try (InputStream is = propsUrl.openStream()) {
            props.load(is);
        }
        final String PLACEHOLDER = "__INJECT_AT_TEST_TIME__";
        if (PLACEHOLDER.equals(props.getProperty("mysqlpoolname.password", ""))) {
            props.setProperty("mysqlpoolname.password", pw);
        }
        java.io.File propsFile = new java.io.File(propsUrl.toURI());
        try (java.io.FileOutputStream fos = new java.io.FileOutputStream(propsFile)) {
            props.store(fos, "Auto-generated by DerivedViewBackedReportTest");
        }

        ConnectionPool.getInstance();

        // Auto-discover a non-bot user with a PLAYER_VIN account so the test
        // is portable across environments (5107 is the dual-write fixture id
        // and may not exist locally).
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT u.id, u.nick_name FROM vinplay.users u "
                             + "JOIN vinplay.money_account ma ON ma.owner_user_id=u.id "
                             + "  AND ma.account_type='PLAYER_VIN' AND ma.is_system=0 "
                             + "WHERE u.is_bot=0 ORDER BY u.id LIMIT 1");
             ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                testUserId = rs.getLong("id");
                testNickname = rs.getString("nick_name");
                System.out.println("DerivedViewBackedReportTest: using test user "
                        + testNickname + " (id=" + testUserId + ")");
            } else {
                bootstrapSkipped = true;
                System.out.println("DerivedViewBackedReportTest: no user with PLAYER_VIN account found; tests will be skipped");
            }
        }
    }

    @AfterClass
    public static void cleanUp() {
        if (bootstrapSkipped) return;

        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname")) {
            try (PreparedStatement ps = conn.prepareStatement(
                    "DELETE e FROM vinplay.money_entry e"
                    + " JOIN vinplay.money_transaction t ON t.transaction_id = e.transaction_id"
                    + " WHERE t.external_ref LIKE '" + REF_PREFIX + "%'")) {
                ps.executeUpdate();
            }
            try (PreparedStatement ps = conn.prepareStatement(
                    "DELETE FROM vinplay.money_transaction WHERE external_ref LIKE '" + REF_PREFIX + "%'")) {
                ps.executeUpdate();
            }
        } catch (Exception e) {
            System.err.println("DerivedViewBackedReportTest cleanup error (non-fatal): " + e.getMessage());
        }

        // Restore placeholder
        try {
            URL propsUrl = DerivedViewBackedReportTest.class
                    .getClassLoader()
                    .getResource("config/db_pool.properties");
            if (propsUrl != null) {
                Properties props = new Properties();
                try (InputStream is = propsUrl.openStream()) {
                    props.load(is);
                }
                props.setProperty("mysqlpoolname.password", "__INJECT_AT_TEST_TIME__");
                java.io.File propsFile = new java.io.File(propsUrl.toURI());
                try (java.io.FileOutputStream fos = new java.io.FileOutputStream(propsFile)) {
                    props.store(fos, "Placeholder restored");
                }
            }
        } catch (Exception ignore) {
        }
    }

    @Before
    public void skipIfNoPassword() {
        Assume.assumeFalse(
                "test.mysql.password or MYSQL_PASSWORD must be set",
                bootstrapSkipped);
    }

    /**
     * Insert a DEPOSIT_BANK transaction + corresponding CREDIT money_entry
     * into the test user's PLAYER_VIN account.  Returns the external_ref.
     */
    private String insertDepositLedgerRow(long amount) throws Exception {
        String externalRef = REF_PREFIX + System.nanoTime();
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname")) {
            // Look up the user's PLAYER_VIN account
            long accountId;
            try (PreparedStatement ps = conn.prepareStatement(
                    "SELECT account_id FROM vinplay.money_account "
                            + "WHERE owner_user_id=? AND account_type='PLAYER_VIN' "
                            + "AND is_system=0 LIMIT 1")) {
                ps.setLong(1, testUserId);
                try (ResultSet rs = ps.executeQuery()) {
                    Assume.assumeTrue("test user must have a PLAYER_VIN account", rs.next());
                    accountId = rs.getLong("account_id");
                }
            }

            long txId;
            try (PreparedStatement ps = conn.prepareStatement(
                    "INSERT INTO vinplay.money_transaction "
                            + "(external_ref, transaction_type, status, posted_at) "
                            + "VALUES (?, 'DEPOSIT_BANK', 'POSTED', NOW(6))",
                    java.sql.Statement.RETURN_GENERATED_KEYS)) {
                ps.setString(1, externalRef);
                ps.executeUpdate();
                try (ResultSet rs = ps.getGeneratedKeys()) {
                    rs.next();
                    txId = rs.getLong(1);
                }
            }

            try (PreparedStatement ps = conn.prepareStatement(
                    "INSERT INTO vinplay.money_entry "
                            + "(transaction_id, account_id, direction, amount, balance_before, balance_after, created_at) "
                            + "VALUES (?, ?, 'CREDIT', ?, 0, ?, NOW(6))")) {
                ps.setLong(1, txId);
                ps.setLong(2, accountId);
                ps.setLong(3, amount);
                ps.setLong(4, amount);
                ps.executeUpdate();
            }
        }
        return externalRef;
    }

    /**
     * Query the v_derived_deposit_total view directly for the test user.
     */
    private long readDerivedDepositTotal() throws Exception {
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT COALESCE(deposit_total, 0) AS dt FROM v_derived_deposit_total WHERE user_id=?")) {
            ps.setLong(1, testUserId);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? rs.getLong("dt") : 0L;
            }
        }
    }

    @Test
    public void testTopRechargeMoney_DerivedFromLedger() throws Exception {
        long before = readDerivedDepositTotal();

        // Seed a fresh DEPOSIT_BANK row in the ledger
        insertDepositLedgerRow(TEST_DEPOSIT_AMOUNT);

        long after = readDerivedDepositTotal();
        assertEquals("view must reflect newly-inserted DEPOSIT_BANK row",
                before + TEST_DEPOSIT_AMOUNT, after);

        // Filter by nickname so the test isn't fragile against other top spenders
        TopRechargeMoneyDAO dao = new TopRechargeMoneyDAOImpl();
        List<TopRechargeMoneyResponse> rows = dao.getTopRechargeMoney(50, testNickname, 1, -1);

        assertNotNull(rows);
        assertTrue("test user must appear in TopRechargeMoney result", rows.size() >= 1);
        TopRechargeMoneyResponse top = rows.get(0);
        assertEquals(testNickname, top.userName);
        assertEquals("DAO must return deposit_total from v_derived_deposit_total",
                after, top.money);
    }
}
