package com.vinplay.dal.dao.impl;

import com.vinplay.dal.entities.gsc.GscBet;
import com.vinplay.vbee.common.config.VBeePath;
import com.vinplay.vbee.common.pools.ConnectionPool;
import org.junit.AfterClass;
import org.junit.Assume;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.util.List;
import java.util.Properties;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

/**
 * Integration tests for {@link GscBetsDaoImpl} — the MySQL DAO for the
 * cross-store traceability follow-up #5.
 *
 * <p>Bootstrap mirrors {@code MoneyGatewayDualWriteTest} (Phase 0
 * pattern): supply the password via {@code -Dtest.mysql.password=…} or
 * {@code MYSQL_PASSWORD} env. Without it the suite is <em>skipped</em>
 * (not failed) via {@link Assume}.
 *
 * <pre>
 *   ./gradlew :VinPlayDAL:test --tests GscBetsDaoImplTest \
 *      -Dtest.mysql.password=$(grep MYSQL_PASSWORD /path/to/.env | cut -d= -f2)
 * </pre>
 *
 * <p>Coverage:
 * <ul>
 *   <li>insert + findByUserName roundtrip</li>
 *   <li>duplicate wager_code → INSERT IGNORE no-op (false return, no
 *       throw, single row in DB)</li>
 *   <li>settle → settled=true, prize incremented, settle_txn_id set</li>
 *   <li>deleteByWagerCode</li>
 *   <li>findUnsettledOlderThan returns expected rows ordered ASC by
 *       create_time</li>
 *   <li>deleteByFilter (SUN-1184 free-spin cleanup)</li>
 * </ul>
 *
 * <p>All test rows use the {@code TEST_PREFIX} on {@code wager_code} so
 * the {@link AfterClass} sweep cleans them up without touching real data.
 */
public class GscBetsDaoImplTest {

    private static final String TEST_PREFIX = "test_gsc_bets_dao_";

    private static volatile boolean bootstrapSkipped = false;

    @BeforeClass
    public static void bootstrapPool() throws Exception {
        String pw = System.getProperty("test.mysql.password");
        if (pw == null || pw.isEmpty()) pw = System.getenv("MYSQL_PASSWORD");
        if (pw == null || pw.isEmpty()) {
            bootstrapSkipped = true;
            System.out.println("GscBetsDaoImplTest: password not supplied; tests will be skipped");
            return;
        }

        URL propsUrl = GscBetsDaoImplTest.class.getClassLoader()
                .getResource("config/db_pool.properties");
        assertNotNull("config/db_pool.properties must be on the classpath", propsUrl);
        String resourcesDir = propsUrl.getPath().replace("config/db_pool.properties", "");
        VBeePath.basePath = resourcesDir;

        Properties props = new Properties();
        try (InputStream is = propsUrl.openStream()) {
            props.load(is);
        }
        final String PLACEHOLDER = "__INJECT_AT_TEST_TIME__";
        if (PLACEHOLDER.equals(props.getProperty("mysqlpoolname.password", ""))) {
            props.setProperty("mysqlpoolname.password", pw);
        }
        java.io.File propsFile = new java.io.File(propsUrl.toURI());
        try (java.io.FileOutputStream fos = new java.io.FileOutputStream(propsFile)) {
            props.store(fos, "Auto-generated by GscBetsDaoImplTest — password injected at test time");
        }

        ConnectionPool.getInstance();
    }

    @AfterClass
    public static void cleanUp() {
        if (bootstrapSkipped) return;

        // Restore the placeholder so the file isn't checked in with a real password
        try {
            URL propsUrl = GscBetsDaoImplTest.class.getClassLoader()
                    .getResource("config/db_pool.properties");
            if (propsUrl != null) {
                Properties props = new Properties();
                try (InputStream is = propsUrl.openStream()) {
                    props.load(is);
                }
                props.setProperty("mysqlpoolname.password", "__INJECT_AT_TEST_TIME__");
                java.io.File propsFile = new java.io.File(propsUrl.toURI());
                try (java.io.FileOutputStream fos = new java.io.FileOutputStream(propsFile)) {
                    props.store(fos,
                            "Integration-test DB pool — password placeholder restored after run");
                }
            }
        } catch (Exception e) {
            System.err.println("GscBetsDaoImplTest: could not restore placeholder (non-fatal): "
                    + e.getMessage());
        }

        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "DELETE FROM vinplay.gsc_bets WHERE wager_code LIKE ?")) {
            ps.setString(1, TEST_PREFIX + "%");
            int n = ps.executeUpdate();
            System.out.println("GscBetsDaoImplTest cleanup: deleted " + n + " rows");
        } catch (Exception e) {
            System.err.println("GscBetsDaoImplTest cleanup error (non-fatal): " + e.getMessage());
        }
    }

    @Before
    public void skipIfNoPassword() {
        Assume.assumeFalse(
                "test.mysql.password or MYSQL_PASSWORD must be set", bootstrapSkipped);
    }

    private final GscBetsDaoImpl dao = new GscBetsDaoImpl();

    /** Build a GscBet seeded with a unique-ish wager code under the test prefix. */
    private GscBet sampleBet(String suffix) {
        GscBet b = new GscBet();
        b.userId = 999_001L;
        b.userName = "it_gsc_user_" + suffix;
        b.nickName = "it_gsc_user_" + suffix;
        b.betValue = 10_000L;
        b.prize = 0L;
        b.fee = 0L;
        b.productCode = 1052;
        b.gameCode = "10302";
        b.gameKey = "gsc_1052_10302";
        b.gameName = "Dream Baccarat";
        b.txnId = "tx_" + suffix;
        b.wagerCode = TEST_PREFIX + suffix;
        b.currency = "VND";
        b.betType = "BET";
        b.settled = false;
        b.eventKey = "gsc:1052:10302:" + b.wagerCode;
        b.createTime = new Date();
        b.timeLog = b.createTime;
        return b;
    }

    private int countRowsByWager(String wagerCode) throws Exception {
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT COUNT(*) FROM vinplay.gsc_bets WHERE wager_code = ?")) {
            ps.setString(1, wagerCode);
            try (ResultSet rs = ps.executeQuery()) {
                rs.next();
                return rs.getInt(1);
            }
        }
    }

    // -----------------------------------------------------------------

    @Test
    public void testInsertAndReadBack() throws Exception {
        GscBet bet = sampleBet("ins1");
        // Pre-clean in case of a previous failed run
        dao.deleteByWagerCode(bet.wagerCode);

        boolean inserted = dao.insert(bet);
        assertTrue("first insert should succeed", inserted);

        List<GscBet> rows = dao.findByUserName(bet.userName, 10, 0);
        assertEquals(1, rows.size());
        GscBet read = rows.get(0);
        assertEquals(bet.wagerCode, read.wagerCode);
        assertEquals(bet.betValue, read.betValue);
        assertEquals(0L, read.prize);
        assertFalse(read.settled);
        assertEquals(bet.eventKey, read.eventKey);
        assertEquals(bet.gameKey, read.gameKey);
        assertEquals(bet.productCode, read.productCode);
    }

    @Test
    public void testInsertDuplicateWagerCodeIsIgnored() throws Exception {
        GscBet bet = sampleBet("dup1");
        dao.deleteByWagerCode(bet.wagerCode);

        assertTrue(dao.insert(bet));
        // Second insert with the SAME wager_code must not throw and must
        // not create a second row.
        boolean second = dao.insert(bet);
        assertFalse("duplicate wager_code should be a no-op (INSERT IGNORE)", second);
        assertEquals("UNIQUE wager_code → exactly one row", 1, countRowsByWager(bet.wagerCode));
    }

    @Test
    public void testSettleUpdate() throws Exception {
        GscBet bet = sampleBet("settle1");
        dao.deleteByWagerCode(bet.wagerCode);

        assertTrue(dao.insert(bet));

        int updated = dao.settle(bet.userName, bet.productCode, bet.gameCode,
                bet.wagerCode, bet.eventKey, null, 25_000L, "settle_tx_settle1");
        assertEquals("settle should update exactly one row", 1, updated);

        // Verify the settled row state.
        List<GscBet> rows = dao.findByUserName(bet.userName, 10, 0);
        assertEquals(1, rows.size());
        GscBet read = rows.get(0);
        assertTrue("settled must be true after settle", read.settled);
        assertEquals(25_000L, read.prize);
        assertEquals("settle_tx_settle1", read.settleTxnId);
        assertNotNull("settle_time must be stamped", read.settleTime);

        // Re-settle adds to prize ($inc semantics) — mirror Mongo's $inc.
        dao.settle(bet.userName, bet.productCode, bet.gameCode,
                bet.wagerCode, bet.eventKey, null, 5_000L, "settle_tx_settle1_2");
        rows = dao.findByUserName(bet.userName, 10, 0);
        assertEquals(30_000L, rows.get(0).prize);
    }

    @Test
    public void testDeleteByWagerCode() throws Exception {
        GscBet bet = sampleBet("del1");
        dao.deleteByWagerCode(bet.wagerCode);

        assertTrue(dao.insert(bet));
        assertEquals(1, countRowsByWager(bet.wagerCode));

        int deleted = dao.deleteByWagerCode(bet.wagerCode);
        assertEquals(1, deleted);
        assertEquals(0, countRowsByWager(bet.wagerCode));

        // Deleting a non-existent wager is a 0-row no-op (matches
        // Mongo deleteMany on an empty filter set).
        assertEquals(0, dao.deleteByWagerCode(bet.wagerCode));
    }

    @Test
    public void testFindUnsettledOlderThan() throws Exception {
        // Seed three rows: two old + unsettled, one new + unsettled, one old + settled.
        GscBet oldUnsettledA = sampleBet("uns_oldA");
        GscBet oldUnsettledB = sampleBet("uns_oldB");
        GscBet newUnsettled = sampleBet("uns_new");
        GscBet oldSettled  = sampleBet("uns_oldS");

        // Backdate the "old" rows so the cutoff scan picks them.
        long now = System.currentTimeMillis();
        oldUnsettledA.createTime = new Date(now - 60 * 60_000L);   // 1h ago
        oldUnsettledB.createTime = new Date(now - 30 * 60_000L);   // 30m ago
        oldSettled.createTime    = new Date(now - 60 * 60_000L);
        newUnsettled.createTime  = new Date(now);                  // now

        for (GscBet b : new GscBet[]{ oldUnsettledA, oldUnsettledB, newUnsettled, oldSettled }) {
            dao.deleteByWagerCode(b.wagerCode);
            dao.insert(b);
        }
        // Settle one of them so the scan must skip it.
        dao.settle(oldSettled.userName, oldSettled.productCode, oldSettled.gameCode,
                oldSettled.wagerCode, oldSettled.eventKey, null, 100L, "x");

        // Cutoff = 10 minutes ago — should match the two old + unsettled rows.
        Date cutoff = new Date(now - 10 * 60_000L);
        List<GscBet> found = dao.findUnsettledOlderThan(cutoff, 50);
        // Filter to only our test rows so any prod data on the live DB is ignored.
        long matches = found.stream()
                .filter(b -> b.wagerCode != null && b.wagerCode.startsWith(TEST_PREFIX + "uns_"))
                .count();
        assertEquals("two old + unsettled rows expected", 2L, matches);

        // Verify ordering — oldest first. Filter to test rows.
        java.util.List<GscBet> filtered = new java.util.ArrayList<>();
        for (GscBet b : found) {
            if (b.wagerCode != null && b.wagerCode.startsWith(TEST_PREFIX + "uns_")) {
                filtered.add(b);
            }
        }
        assertTrue(filtered.size() >= 2);
        assertEquals(oldUnsettledA.wagerCode, filtered.get(0).wagerCode);
        assertEquals(oldUnsettledB.wagerCode, filtered.get(1).wagerCode);
    }

    @Test
    public void testDeleteByFilterFreespinCleanup() throws Exception {
        // SUN-1184 — bet_value=0 row should drop; bet_value>0 row should stay.
        GscBet zero = sampleBet("fs_zero");
        zero.betValue = 0L;
        GscBet nonzero = sampleBet("fs_nonzero");
        nonzero.betValue = 5_000L;
        nonzero.userName = zero.userName;          // same user filter
        nonzero.productCode = zero.productCode;
        nonzero.gameCode = zero.gameCode;

        dao.deleteByWagerCode(zero.wagerCode);
        dao.deleteByWagerCode(nonzero.wagerCode);
        dao.insert(zero);
        dao.insert(nonzero);

        // Filter on the user+product+game — the bet_value=0 guard inside
        // deleteByFilter ensures only the zero row drops.
        int deleted = dao.deleteByFilter(zero.userName, zero.productCode, zero.gameCode, null);
        assertEquals(1, deleted);
        assertEquals(0, countRowsByWager(zero.wagerCode));
        assertEquals(1, countRowsByWager(nonzero.wagerCode));
    }
}
