package com.vinplay.dal.service.seamless;

import com.vinplay.dal.service.MoneyGateway;
import com.vinplay.vbee.common.config.VBeePath;
import com.vinplay.vbee.common.pools.ConnectionPool;
import org.junit.AfterClass;
import org.junit.Assume;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import javax.servlet.http.HttpServletRequest;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

/**
 * Phase 1 scaffolding test — no production callers exist yet, this just
 * exercises the {@link SeamlessWalletAggregator} base class via tiny
 * concrete test subclasses.
 *
 * <p>Three tests:
 * <ol>
 *   <li>{@link #testDuplicateExternalRef_returnsDuplicateOutcomeBalanceUnchanged}
 *       — call {@code handle} twice with the same {@code externalRef}; second
 *       call returns DUPLICATE; only one money_gateway_log row was written.
 *   <li>{@link #testSignatureError_shortCircuitsBeforeWalletCall}
 *       — when {@code verifySignature} fails, {@code dispatch} is never
 *       invoked (counter stays at 0); outcome is SIGNATURE_ERROR.
 *   <li>{@link #testDoDebit_insufficientBalance_mapsToInsufficientOutcome}
 *       — {@code doDebit} for an amount larger than the user's balance maps
 *       to INSUFFICIENT_BALANCE and {@code serializeResponse} sees that
 *       outcome.
 * </ol>
 *
 * <p>Same {@code Assume.assumeFalse(bootstrapSkipped)} pattern as
 * {@link com.vinplay.dal.service.MoneyGatewayDualWriteTest}; tests skip when
 * the DB password isn't supplied.
 */
public class SeamlessWalletAggregatorTest {

    /**
     * User id with a PLAYER_VIN money_account (seeded by task #176).
     *
     * <p>The aggregator's {@code doDebit/doCredit} resolve via
     * {@code users.user_name} → {@code (id, nick_name)}, so the test reads
     * {@code TEST_USERNAME} / {@code TEST_NICKNAME} directly from the DB at
     * {@code @BeforeClass} time rather than hard-coding values that would
     * drift across seed snapshots. If the row doesn't exist, every test
     * {@code Assume}-skips.
     */
    private static final long TEST_USER_ID = 5107L;
    private static volatile String TEST_USERNAME;
    private static volatile String TEST_NICKNAME;

    private static final String REF_PREFIX = "test_swa_";

    private static volatile boolean bootstrapSkipped = false;

    @BeforeClass
    public static void bootstrapPool() throws Exception {
        String pw = System.getProperty("test.mysql.password");
        if (pw == null || pw.isEmpty()) {
            pw = System.getenv("MYSQL_PASSWORD");
        }
        if (pw == null || pw.isEmpty()) {
            bootstrapSkipped = true;
            System.out.println("SeamlessWalletAggregatorTest: password not supplied; tests will be skipped");
            return;
        }

        URL propsUrl = SeamlessWalletAggregatorTest.class
                .getClassLoader()
                .getResource("config/db_pool.properties");
        String resourcesDir = propsUrl.getPath().replace("config/db_pool.properties", "");
        VBeePath.basePath = resourcesDir;

        Properties props = new Properties();
        try (InputStream is = propsUrl.openStream()) {
            props.load(is);
        }
        final String PLACEHOLDER = "__INJECT_AT_TEST_TIME__";
        if (PLACEHOLDER.equals(props.getProperty("mysqlpoolname.password", ""))) {
            props.setProperty("mysqlpoolname.password", pw);
        }
        java.io.File propsFile = new java.io.File(propsUrl.toURI());
        try (java.io.FileOutputStream fos = new java.io.FileOutputStream(propsFile)) {
            props.store(fos, "Auto-generated by SeamlessWalletAggregatorTest — password injected at test time");
        }

        ConnectionPool.getInstance();

        // Resolve TEST_USERNAME / TEST_NICKNAME from the DB so the test does
        // not hard-code seed-specific values. If the row doesn't exist, leave
        // both null — the per-test @Before will Assume-skip.
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT user_name, nick_name FROM vinplay.users WHERE id = ?")) {
            ps.setLong(1, TEST_USER_ID);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    TEST_USERNAME = rs.getString("user_name");
                    String nick = rs.getString("nick_name");
                    TEST_NICKNAME = (nick != null && !nick.isEmpty()) ? nick : TEST_USERNAME;
                }
            }
        }
    }

    @AfterClass
    public static void cleanUp() {
        if (bootstrapSkipped) return;

        // Restore the placeholder
        try {
            URL propsUrl = SeamlessWalletAggregatorTest.class
                    .getClassLoader()
                    .getResource("config/db_pool.properties");
            if (propsUrl != null) {
                Properties props = new Properties();
                try (InputStream is = propsUrl.openStream()) {
                    props.load(is);
                }
                props.setProperty("mysqlpoolname.password", "__INJECT_AT_TEST_TIME__");
                java.io.File propsFile = new java.io.File(propsUrl.toURI());
                try (java.io.FileOutputStream fos = new java.io.FileOutputStream(propsFile)) {
                    props.store(fos,
                            "Integration-test DB pool — password placeholder restored after run");
                }
            }
        } catch (Exception e) {
            System.err.println("SeamlessWalletAggregatorTest: could not restore placeholder (non-fatal): "
                    + e.getMessage());
        }

        // Wipe any test rows created by this suite
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname")) {
            try (PreparedStatement ps = conn.prepareStatement(
                    "DELETE FROM vinplay.money_gateway_log WHERE tx_id LIKE '" + REF_PREFIX + "%'")) {
                int rows = ps.executeUpdate();
                System.out.println("SeamlessWalletAggregatorTest cleanup: deleted " + rows
                        + " money_gateway_log rows");
            }
        } catch (Exception e) {
            System.err.println("SeamlessWalletAggregatorTest cleanup error (non-fatal): " + e.getMessage());
        }
    }

    @Before
    public void skipIfNoPassword() {
        Assume.assumeFalse(
                "test.mysql.password or MYSQL_PASSWORD must be set. "
                + "Run: ./gradlew :VinPlayDAL:test --tests SeamlessWalletAggregatorTest "
                + "-Dtest.mysql.password=$(grep MYSQL_PASSWORD /path/to/.env | cut -d= -f2)",
                bootstrapSkipped);
        Assume.assumeNotNull(
                "users.id=" + TEST_USER_ID + " row must exist (seed via task #176)",
                TEST_USERNAME);
    }

    // -----------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------

    /**
     * Build an {@link HttpServletRequest} via dynamic proxy so the test
     * doesn't depend on jetty / mockito. Only the methods the aggregator
     * actually calls ({@code getReader}) are wired; everything else returns
     * a default value.
     */
    private static HttpServletRequest mockRequest(final String body) {
        return (HttpServletRequest) Proxy.newProxyInstance(
                HttpServletRequest.class.getClassLoader(),
                new Class<?>[]{HttpServletRequest.class},
                new InvocationHandler() {
                    @Override
                    public Object invoke(Object p, Method m, Object[] a) throws Throwable {
                        if ("getReader".equals(m.getName())) {
                            return new BufferedReader(new InputStreamReader(
                                    new ByteArrayInputStream(body.getBytes(StandardCharsets.UTF_8)),
                                    StandardCharsets.UTF_8));
                        }
                        // Default value for unused methods (boolean → false, int → 0, …).
                        Class<?> ret = m.getReturnType();
                        if (ret == boolean.class) return Boolean.FALSE;
                        if (ret == int.class) return Integer.valueOf(0);
                        if (ret == long.class) return Long.valueOf(0L);
                        if (ret == void.class) return null;
                        if (ret.isPrimitive()) return Integer.valueOf(0);
                        return null;
                    }
                });
    }

    private int countLegacyRows(String txId) throws Exception {
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT COUNT(*) FROM vinplay.money_gateway_log WHERE tx_id = ?")) {
            ps.setString(1, txId);
            try (ResultSet rs = ps.executeQuery()) {
                rs.next();
                return rs.getInt(1);
            }
        }
    }

    private long readVin(long userId) throws Exception {
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement("SELECT vin FROM vinplay.users WHERE id = ?")) {
            ps.setLong(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                rs.next();
                return rs.getLong(1);
            }
        }
    }

    private void cleanTxId(String txId) throws Exception {
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "DELETE FROM vinplay.money_gateway_log WHERE tx_id = ?")) {
            ps.setString(1, txId);
            ps.executeUpdate();
        }
    }

    /**
     * Tiny test aggregator: the request "body" IS the externalRef. Hooks
     * are wired by the test via lambda-like fields. Uses
     * {@link MoneyGateway#SOURCE_AWC_DEBIT} as the source (an existing
     * source-constant; no need to register a new one for tests).
     */
    private static final class TestAggregator extends SeamlessWalletAggregator<String, String> {
        VerifyResult verifyResult = VerifyResult.ok();
        ValidationResult validationResult = ValidationResult.ok();
        AtomicInteger dispatchCount = new AtomicInteger(0);
        AtomicReference<SeamlessOutcome> lastSerialized = new AtomicReference<>();
        // Action the dispatch performs: "debit" / "credit" / "noop".
        String action = "debit";
        long amount = 1L;
        String txId = "ignored";
        String username = TEST_USERNAME;

        @Override protected String parseRequest(String body, HttpServletRequest http) {
            return body;
        }
        @Override protected VerifyResult verifySignature(String req, HttpServletRequest http) {
            return verifyResult;
        }
        @Override protected ValidationResult validateBusinessRules(String req) {
            return validationResult;
        }
        @Override protected long currencyToInternal(double providerAmount, String currency) {
            return (long) providerAmount;
        }
        @Override protected double currencyToExternal(long internalBalance, String currency) {
            return (double) internalBalance;
        }
        @Override protected String mapActionToSource(String a) {
            return MoneyGateway.SOURCE_AWC_DEBIT;
        }
        @Override protected String serializeResponse(SeamlessOutcome out) {
            lastSerialized.set(out);
            return "{\"status\":\"" + out.status + "\",\"balance\":" + out.newBalance + "}";
        }
        @Override protected SeamlessOutcome dispatch(String req) {
            dispatchCount.incrementAndGet();
            if ("debit".equals(action)) {
                SeamlessTxn txn = new SeamlessTxn(username, txId, "bet", amount, "VND", null);
                return doDebit(txn);
            } else if ("credit".equals(action)) {
                SeamlessTxn txn = new SeamlessTxn(username, txId, "settle", amount, "VND", null);
                return doCredit(txn);
            } else {
                return doReadBalance(username);
            }
        }
    }

    // -----------------------------------------------------------------
    // Test 1: duplicate externalRef → DUPLICATE outcome, balance unchanged
    // -----------------------------------------------------------------

    /**
     * Provider replays the same callback twice. Audit-#17 dedup at the
     * gateway must turn the second call into a DUPLICATE outcome with
     * exactly one wallet movement and exactly one money_gateway_log row.
     */
    @Test
    public void testDuplicateExternalRef_returnsDuplicateOutcomeBalanceUnchanged() throws Exception {
        String txId = REF_PREFIX + "dup_001";
        cleanTxId(txId);
        long amount = 17L;

        // Pre-fund the user so the debit's floor-check passes.
        MoneyGateway.CreditResult prefund = MoneyGateway.creditUser(
                TEST_USER_ID, TEST_NICKNAME, amount,
                MoneyGateway.SOURCE_ADMIN_TOPUP, txId + "_setup",
                "SeamlessWalletAggregatorTest dup pre-fund");
        Assume.assumeTrue("pre-fund must succeed",
                prefund != null && prefund.success);

        TestAggregator agg = new TestAggregator();
        agg.action = "debit";
        agg.amount = amount;
        agg.txId = txId;

        long balBefore = readVin(TEST_USER_ID);

        try {
            // First call — POSTED, balance dropped by amount.
            String resp1 = agg.handle(mockRequest("ignored"));
            assertNotNull(resp1);
            SeamlessOutcome out1 = agg.lastSerialized.get();
            assertEquals("first call must be POSTED", SeamlessOutcome.Status.POSTED, out1.status);
            assertEquals(balBefore - amount, readVin(TEST_USER_ID));

            // Second call — same txId, must DUPLICATE; balance unchanged from after-first-call.
            String resp2 = agg.handle(mockRequest("ignored"));
            assertNotNull(resp2);
            SeamlessOutcome out2 = agg.lastSerialized.get();
            assertEquals("second call must be DUPLICATE", SeamlessOutcome.Status.DUPLICATE, out2.status);

            assertEquals("users.vin must be debited by exactly 1x amount, not 2x",
                    balBefore - amount, readVin(TEST_USER_ID));
            assertEquals("money_gateway_log must have exactly 1 row for the txId",
                    1, countLegacyRows(txId));
        } finally {
            // Reverse the debit so users.vin is unchanged for downstream tests.
            try {
                MoneyGateway.creditUser(
                        TEST_USER_ID, TEST_NICKNAME, amount,
                        MoneyGateway.SOURCE_ADMIN_TOPUP, txId + "_undo",
                        "SeamlessWalletAggregatorTest dup undo");
            } catch (Exception ignore) { /* best effort */ }
        }
    }

    // -----------------------------------------------------------------
    // Test 2: signature error short-circuits before wallet call
    // -----------------------------------------------------------------

    /**
     * When {@code verifySignature} returns {@code !ok}, the base class must
     * never reach {@link SeamlessWalletAggregator#dispatch}. Counter stays
     * at 0; outcome is SIGNATURE_ERROR; no money_gateway_log row.
     */
    @Test
    public void testSignatureError_shortCircuitsBeforeWalletCall() throws Exception {
        String txId = REF_PREFIX + "sig_001";
        cleanTxId(txId);

        TestAggregator agg = new TestAggregator();
        agg.verifyResult = VerifyResult.fail("bad sig");
        agg.action = "debit";
        agg.amount = 1L;
        agg.txId = txId;

        String resp = agg.handle(mockRequest("ignored"));
        assertNotNull(resp);

        assertEquals("dispatch must NOT be called when signature fails",
                0, agg.dispatchCount.get());

        SeamlessOutcome out = agg.lastSerialized.get();
        assertNotNull("serializeResponse must still receive a SIGNATURE_ERROR outcome", out);
        assertEquals("outcome must be SIGNATURE_ERROR",
                SeamlessOutcome.Status.SIGNATURE_ERROR, out.status);
        assertEquals("error message must be propagated from VerifyResult",
                "bad sig", out.errorMessage);

        assertEquals("no money_gateway_log row may be written",
                0, countLegacyRows(txId));
    }

    // -----------------------------------------------------------------
    // Test 3: doDebit insufficient balance → INSUFFICIENT_BALANCE outcome
    // -----------------------------------------------------------------

    /**
     * Debit amount larger than the user's balance must surface as
     * {@link SeamlessOutcome.Status#INSUFFICIENT_BALANCE} and
     * {@code serializeResponse} must see that outcome.
     *
     * <p>To make the test deterministic we don't try to assert "amount is
     * exactly N more than balance" — instead we use {@code Long.MAX_VALUE}
     * which will always exceed any real {@code users.vin} value.
     */
    @Test
    public void testDoDebit_insufficientBalance_mapsToInsufficientOutcome() throws Exception {
        String txId = REF_PREFIX + "insuf_001";
        cleanTxId(txId);

        TestAggregator agg = new TestAggregator();
        agg.action = "debit";
        agg.amount = Long.MAX_VALUE; // Definitely more than any real vin balance.
        agg.txId = txId;

        long balBefore = readVin(TEST_USER_ID);
        String resp = agg.handle(mockRequest("ignored"));
        assertNotNull(resp);

        SeamlessOutcome out = agg.lastSerialized.get();
        assertNotNull(out);
        assertEquals("debit > balance must map to INSUFFICIENT_BALANCE",
                SeamlessOutcome.Status.INSUFFICIENT_BALANCE, out.status);

        assertEquals("users.vin must be unchanged when debit is rejected",
                balBefore, readVin(TEST_USER_ID));
        assertEquals("no money_gateway_log row must be written when debit is rejected",
                0, countLegacyRows(txId));

        // Sanity: the outcome's errorCode is null (insufficientBalance factory
        // doesn't set one); errorMessage is null too. The subclass owns the
        // mapping to a provider error code in serializeResponse.
        assertNull(out.errorCode);
    }

    // -----------------------------------------------------------------
    // Smoke test: doReadBalance returns POSTED with the current balance
    // -----------------------------------------------------------------

    /**
     * Bonus smoke test for the read-only path: doReadBalance returns POSTED
     * with users.vin and writes nothing. Helps catch regressions in the
     * read-only primitive without bringing in DB-write side-effects.
     */
    @Test
    public void testDoReadBalance_returnsPostedWithCurrentBalance() throws Exception {
        TestAggregator agg = new TestAggregator();
        agg.action = "noop"; // dispatch will route to doReadBalance

        String resp = agg.handle(mockRequest("ignored"));
        assertNotNull(resp);

        SeamlessOutcome out = agg.lastSerialized.get();
        assertNotNull(out);
        assertEquals(SeamlessOutcome.Status.POSTED, out.status);

        long actual = readVin(TEST_USER_ID);
        assertEquals("doReadBalance must echo users.vin", actual, out.newBalance);
        assertTrue("dispatch must have been called exactly once", agg.dispatchCount.get() == 1);
    }
}
