package com.vinplay.dal.service;

import com.vinplay.vbee.common.config.VBeePath;
import com.vinplay.vbee.common.pools.ConnectionPool;
import org.junit.AfterClass;
import org.junit.Assume;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

/**
 * SUN-1054 / Wallet Phase 5c — Java-side min-balance enforcement for BanCa.
 *
 * <p>After Phase 5c the C# {@code LobbyService.cs} cashout "remain" pre-check
 * was removed (the legacy clamp that refused to debit a player below zero).
 * Java is now the only floor-check. This test pins the contract so a future
 * refactor of {@link MoneyGateway#debitUser} can't accidentally re-introduce
 * the negative-balance bug:
 *
 * <ul>
 *   <li>Attempting to debit more than the user's current {@code users.vin}
 *       returns {@code success=false} with
 *       {@code failureCode=INSUFFICIENT_BALANCE} and {@code error}
 *       containing "Insufficient".</li>
 *   <li>{@code users.vin} is <b>unchanged</b> after the rejected debit.</li>
 *   <li>No row is posted to {@code money_gateway_log} for the rejected debit
 *       (the audit row is INSERTed inside the same transaction as the SQL
 *       UPDATE, so a rolled-back debit MUST NOT leave audit evidence).</li>
 * </ul>
 *
 * <p>Routes through {@code SOURCE_WAGER_DEBIT_BANCA} which is the source
 * tag that {@code BanCaSettleProcessor} (c=9998) hands to
 * {@link MoneyGateway#debitUser} — i.e. this exercises the exact code path
 * that the C# {@code MoneyGatewayClient.SettleAsync} POST lands on for a
 * losing-session settle.
 *
 * <p>Same bootstrap pattern as {@link MoneyGatewayDualWriteTest}: requires a
 * running {@code sunwinkr-mysql} on 127.0.0.1:3306 and a DB password via
 * {@code -Dtest.mysql.password=<pw>} or {@code MYSQL_PASSWORD}. Tests are
 * {@link Assume#assumeFalse skipped} (not failed) when the password is
 * absent so CI doesn't break on hosts without a Docker MySQL.
 *
 * <pre>
 *   ./gradlew :VinPlayDAL:test --tests BanCaSettleMinBalanceTest \
 *      -Dtest.mysql.password=$(grep MYSQL_PASSWORD /root/sunwinkr/sunwinkr/.env | cut -d= -f2)
 * </pre>
 */
public class BanCaSettleMinBalanceTest {

    // Reuse the same canonical test user as MoneyGatewayDualWriteTest so the
    // suite shares one bootstrap path. User 5107 has a PLAYER_VIN account
    // seeded by Phase 0 task #176.
    private static final long TEST_USER_ID = 5107L;
    private static final String TEST_NICKNAME = "testUser5107";

    /** Prefix all txIds so {@link #cleanUp} can strip them safely. */
    private static final String REF_PREFIX = "test_banca_minbal_";

    /** Phase 5c uses milli-VND on the wire; the C# client divides by 1000.
     *  This test calls {@link MoneyGateway#debitUser} directly in VND. */
    private static final long DEBIT_AMOUNT_VND = 1_000_000_000L;

    private static volatile boolean bootstrapSkipped = false;

    @BeforeClass
    public static void bootstrapPool() throws Exception {
        String pw = System.getProperty("test.mysql.password");
        if (pw == null || pw.isEmpty()) pw = System.getenv("MYSQL_PASSWORD");
        if (pw == null || pw.isEmpty()) {
            bootstrapSkipped = true;
            System.out.println("BanCaSettleMinBalanceTest: password not supplied; tests will be skipped");
            return;
        }

        URL propsUrl = BanCaSettleMinBalanceTest.class
                .getClassLoader()
                .getResource("config/db_pool.properties");
        String resourcesDir = propsUrl.getPath().replace("config/db_pool.properties", "");
        VBeePath.basePath = resourcesDir;

        Properties props = new Properties();
        try (InputStream is = propsUrl.openStream()) {
            props.load(is);
        }
        final String PLACEHOLDER = "__INJECT_AT_TEST_TIME__";
        if (PLACEHOLDER.equals(props.getProperty("mysqlpoolname.password", ""))) {
            props.setProperty("mysqlpoolname.password", pw);
        }
        java.io.File propsFile = new java.io.File(propsUrl.toURI());
        try (java.io.FileOutputStream fos = new java.io.FileOutputStream(propsFile)) {
            props.store(fos, "Auto-generated by BanCaSettleMinBalanceTest — password injected at test time");
        }

        ConnectionPool.getInstance();
    }

    @AfterClass
    public static void cleanUp() {
        if (bootstrapSkipped) return;

        // Restore placeholder so the file stays clean between runs.
        try {
            URL propsUrl = BanCaSettleMinBalanceTest.class
                    .getClassLoader()
                    .getResource("config/db_pool.properties");
            if (propsUrl != null) {
                Properties props = new Properties();
                try (InputStream is = propsUrl.openStream()) {
                    props.load(is);
                }
                props.setProperty("mysqlpoolname.password", "__INJECT_AT_TEST_TIME__");
                java.io.File propsFile = new java.io.File(propsUrl.toURI());
                try (java.io.FileOutputStream fos = new java.io.FileOutputStream(propsFile)) {
                    props.store(fos, "Integration-test DB pool — placeholder restored after run");
                }
            }
        } catch (Exception ignore) { /* non-fatal */ }

        // Strip any audit rows this suite may have generated (shouldn't be
        // any — the whole point is no row gets written — but defensive).
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "DELETE FROM vinplay.money_gateway_log WHERE tx_id LIKE '" + REF_PREFIX + "%'")) {
            int rows = ps.executeUpdate();
            System.out.println("BanCaSettleMinBalanceTest cleanup: deleted " + rows + " money_gateway_log rows");
        } catch (Exception e) {
            System.err.println("BanCaSettleMinBalanceTest cleanup error (non-fatal): " + e.getMessage());
        }
    }

    @Before
    public void skipIfNoPassword() {
        Assume.assumeFalse(
                "test.mysql.password or MYSQL_PASSWORD must be set. "
                + "Run: ./gradlew :VinPlayDAL:test --tests BanCaSettleMinBalanceTest "
                + "-Dtest.mysql.password=$(grep MYSQL_PASSWORD /path/to/.env | cut -d= -f2)",
                bootstrapSkipped);
    }

    /**
     * The contract test. Drives the exact call shape that c=9998
     * BanCaSettleProcessor uses for a {@code WAGER_DEBIT_BANCA} of more
     * VND than the player has. MUST be rejected without touching
     * {@code users.vin} and without writing to {@code money_gateway_log}.
     */
    @Test
    public void debitUser_rejectsOverdraft_doesNotMutateBalanceOrAudit() throws Exception {
        long balanceBefore = readVin(TEST_USER_ID);
        // Sanity guard — if the seeded user happens to actually have a
        // billion VND, the "more than they own" assertion is meaningless.
        // Cap the test debit at (balanceBefore + 1) when needed so the
        // overdraft is still strictly larger than the current balance.
        long debit = DEBIT_AMOUNT_VND;
        if (balanceBefore >= debit) {
            debit = balanceBefore + 1L;
        }

        String txId = REF_PREFIX + System.nanoTime();
        MoneyGateway.CreditResult result = MoneyGateway.debitUser(
                TEST_USER_ID,
                TEST_NICKNAME,
                debit,
                MoneyGateway.SOURCE_WAGER_DEBIT_BANCA,
                txId,
                "BanCa overdraft contract test");

        // -- Result shape --
        assertNotNull("debitUser must return a non-null CreditResult", result);
        assertFalse("debit greater than current vin must be rejected", result.success);
        assertEquals("failureCode must be INSUFFICIENT_BALANCE",
                MoneyGateway.CreditResult.ERROR_INSUFFICIENT_BALANCE, result.failureCode);
        assertNotNull("error message must be populated", result.error);
        assertTrue("error message must contain 'Insufficient' (got: " + result.error + ")",
                result.error.contains("Insufficient"));

        // -- users.vin unchanged --
        long balanceAfter = readVin(TEST_USER_ID);
        assertEquals("users.vin MUST be unchanged after a rejected debit",
                balanceBefore, balanceAfter);

        // -- No audit row leaked --
        // The audit INSERT is inside the same SQL transaction as the
        // floor-checked UPDATE; a rejected debit MUST NOT post any row to
        // money_gateway_log.  We key the assertion on (tx_id, source) so a
        // concurrent unrelated debit on the same user does not pollute the
        // count.
        long auditRows = countAuditRows(txId, MoneyGateway.SOURCE_WAGER_DEBIT_BANCA);
        assertEquals("rejected debit must leave zero rows in money_gateway_log",
                0L, auditRows);
    }

    // ------------------------------------------------------------------ helpers

    private static long readVin(long userId) throws Exception {
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement("SELECT vin FROM users WHERE id = ?")) {
            ps.setLong(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                Assume.assumeTrue(
                        "test user " + userId + " not present in vinplay.users",
                        rs.next());
                return rs.getLong(1);
            }
        }
    }

    private static long countAuditRows(String txId, String source) throws Exception {
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT COUNT(*) FROM money_gateway_log WHERE tx_id = ? AND source = ?")) {
            ps.setString(1, txId);
            ps.setString(2, source);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? rs.getLong(1) : 0L;
            }
        }
    }
}
