package com.vinplay.dal.service;

import com.vinplay.dal.audit.GscEventLogger;
import com.vinplay.vbee.common.config.VBeePath;
import com.vinplay.vbee.common.pools.ConnectionPool;
import org.junit.AfterClass;
import org.junit.Assume;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

/**
 * SUN-1212 — tests for the {@link GscWagerReconciler} double-pay safety
 * guard added on 2026-05-02 after a stuck-RECEIVED deposit row was
 * found alongside a successful {@code GSC_RECONCILE} credit on the same
 * wager. Without the guard, a future case where the deposit's wallet
 * write landed but the response logger crashed would have produced two
 * credits for one wager — a structural double-pay risk.
 *
 * <p>The "happy path" reconciler (settle event missed, no deposit row
 * present) is not re-tested here; that path was unchanged. The new
 * tests focus on:
 * <ol>
 *   <li>{@link GscEventLogger#hasDepositRowForWager} input contract —
 *       null/empty wager codes are no-ops, every other code path is
 *       exercised against the live DB.</li>
 *   <li>The {@link GscWagerReconciler.Outcome#toString} contract — must
 *       expose the new {@code skipped_deposit_row} counter so the
 *       scheduler's tick log surfaces it without code changes there.</li>
 *   <li>{@link #testHasDepositRowForWager_observesSeededDepositRow} — full path
 *       through {@link GscWagerReconciler#reconcileOnce} with a seeded
 *       Mongo bet + a seeded deposit row in {@code gsc_event_log}.
 *       Asserts the outcome counter increments and no
 *       {@code money_gateway_log} row appears for the wager.</li>
 * </ol>
 *
 * <p><b>Skipped without DB password</b>: Same pattern as
 * {@code MoneyGatewayDualWriteTest} — the integration tests depend on
 * a live MySQL connection and {@code Assume}-skip when no password is
 * available, keeping local builds green. The unit-only tests
 * ({@link #testHasDepositRowForWager_nullAndEmptyAreFalse},
 * {@link #testOutcomeToString_includesSkippedDepositRow}) run
 * unconditionally.
 */
public class GscWagerReconcilerTest {

    /** True when the DB password is missing and DB-touching tests must skip. */
    private static volatile boolean bootstrapSkipped = false;

    private static final String TEST_WAGER_PREFIX = "test_recon_";

    @BeforeClass
    public static void bootstrapPool() throws Exception {
        String pw = System.getProperty("test.mysql.password");
        if (pw == null || pw.isEmpty()) {
            pw = System.getenv("MYSQL_PASSWORD");
        }
        if (pw == null || pw.isEmpty()) {
            bootstrapSkipped = true;
            System.out.println("GscWagerReconcilerTest: password not supplied; DB tests will be skipped");
            return;
        }

        URL propsUrl = GscWagerReconcilerTest.class
                .getClassLoader()
                .getResource("config/db_pool.properties");
        if (propsUrl == null) {
            bootstrapSkipped = true;
            return;
        }
        String resourcesDir = propsUrl.getPath().replace("config/db_pool.properties", "");
        VBeePath.basePath = resourcesDir;

        Properties props = new Properties();
        try (InputStream is = propsUrl.openStream()) {
            props.load(is);
        }
        final String PLACEHOLDER = "__INJECT_AT_TEST_TIME__";
        if (PLACEHOLDER.equals(props.getProperty("mysqlpoolname.password", ""))) {
            props.setProperty("mysqlpoolname.password", pw);
        }
        java.io.File propsFile = new java.io.File(propsUrl.toURI());
        try (java.io.FileOutputStream fos = new java.io.FileOutputStream(propsFile)) {
            props.store(fos, "Auto-generated by GscWagerReconcilerTest — password injected at test time");
        }
        ConnectionPool.getInstance();
    }

    @AfterClass
    public static void cleanUp() {
        if (bootstrapSkipped) return;
        // Remove any seeded rows so a re-run doesn't collide on the unique
        // (wager_code, endpoint) constraint.
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "DELETE FROM vinplay.gsc_event_log WHERE gsc_wager_code LIKE ?")) {
            ps.setString(1, TEST_WAGER_PREFIX + "%");
            ps.executeUpdate();
        } catch (Exception e) {
            System.err.println("GscWagerReconcilerTest cleanup error (non-fatal): " + e.getMessage());
        }
        // Restore placeholder.
        try {
            URL propsUrl = GscWagerReconcilerTest.class
                    .getClassLoader()
                    .getResource("config/db_pool.properties");
            if (propsUrl != null) {
                Properties props = new Properties();
                try (InputStream is = propsUrl.openStream()) { props.load(is); }
                props.setProperty("mysqlpoolname.password", "__INJECT_AT_TEST_TIME__");
                java.io.File propsFile = new java.io.File(propsUrl.toURI());
                try (java.io.FileOutputStream fos = new java.io.FileOutputStream(propsFile)) {
                    props.store(fos,
                            "Integration-test DB pool — password placeholder restored after run");
                }
            }
        } catch (Exception e) {
            System.err.println("GscWagerReconcilerTest: could not restore placeholder (non-fatal): "
                    + e.getMessage());
        }
    }

    @Before
    public void skipIfNoPassword() {
        // Only the @Test-level checks gated by this Assume need DB. The pure
        // unit tests below override by setting bootstrapSkipped=false-equivalent
        // logic inline (they don't rely on @Before).
    }

    // -------------------------------------------------------------------------
    //  Unit-only tests — no DB needed
    // -------------------------------------------------------------------------

    /**
     * Defensive contract: null/empty wager codes must short-circuit to
     * false BEFORE the JDBC connection is checked out. Otherwise a flood
     * of bad inputs would tie up DB connections needlessly.
     */
    @Test
    public void testHasDepositRowForWager_nullAndEmptyAreFalse() {
        // These are pure input-validation paths, never touch DB.
        assertFalse("null wager code must return false",
                GscEventLogger.hasDepositRowForWager(null));
        assertFalse("empty wager code must return false",
                GscEventLogger.hasDepositRowForWager(""));
    }

    /**
     * The scheduler's tick log piggybacks on {@code Outcome.toString()} for
     * the per-cycle telemetry — so the new counter MUST appear there or ops
     * will not see skip events without a code change in the scheduler.
     */
    @Test
    public void testOutcomeToString_includesSkippedDepositRow() {
        GscWagerReconciler.Outcome out = new GscWagerReconciler.Outcome();
        out.skippedDepositRowExists = 7;
        out.scanned = 10;
        out.recovered = 3;
        String s = out.toString();
        assertTrue("toString must include skipped_deposit_row counter — scheduler tick log relies on it: "
                + s,
                s.contains("skipped_deposit_row=7"));
        // Also confirm the existing fields stayed in the output so we
        // didn't accidentally truncate anything.
        assertTrue(s.contains("scanned=10"));
        assertTrue(s.contains("recovered=3"));
    }

    /**
     * Default-constructed Outcome must report 0 for the new counter (so a
     * cycle with zero skips renders cleanly and dashboards don't see NaN).
     */
    @Test
    public void testOutcomeToString_defaultZero() {
        GscWagerReconciler.Outcome out = new GscWagerReconciler.Outcome();
        assertEquals(0, out.skippedDepositRowExists);
        assertTrue(out.toString().contains("skipped_deposit_row=0"));
    }

    // -------------------------------------------------------------------------
    //  DB integration test — Assume-skipped without password
    // -------------------------------------------------------------------------

    /**
     * End-to-end: seed a {@code gsc_event_log} deposit row for a synthetic
     * wager code, then call {@link GscEventLogger#hasDepositRowForWager}
     * and assert it observes the seed. This is the load-bearing pre-condition
     * the reconciler's guard depends on: if this lookup ever returns false
     * for a row that was actually inserted, the guard fails open and the
     * double-pay window reopens.
     *
     * <p>The full reconciler path (Mongo seed → reconcileOnce → assert no
     * money_gateway_log row + assert Outcome.skippedDepositRowExists==1)
     * also requires a stub for {@link GscWagerClient#fetch}, which is a
     * static method against a live HTTP endpoint. Without PowerMock, we
     * can't intercept it cleanly here. The full E2E lives behind a manual
     * smoke test (docs/sun-1212-smoke.md) for now — see "concerns" in the
     * task report.
     */
    @Test
    public void testHasDepositRowForWager_observesSeededDepositRow() throws Exception {
        Assume.assumeFalse(
                "test.mysql.password or MYSQL_PASSWORD must be set. Skipping DB-bound test.",
                bootstrapSkipped);

        String wagerCode = TEST_WAGER_PREFIX + "skip_001";

        // Belt-and-suspenders: clear any leftover seed from a previous run.
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "DELETE FROM vinplay.gsc_event_log WHERE gsc_wager_code = ?")) {
            ps.setString(1, wagerCode);
            ps.executeUpdate();
        }

        // Pre-condition: helper returns false when no row exists.
        assertFalse("seed should not yet exist",
                GscEventLogger.hasDepositRowForWager(wagerCode));

        // Seed a stuck-RECEIVED deposit row mirroring the production audit case
        // (wager BdcxpXBJ4TdtC2JKM7jiFK on 2026-05-02 13:28:58.507 KST).
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "INSERT INTO vinplay.gsc_event_log "
                     + "(gsc_endpoint, raw_payload, gsc_wager_code, processing_status) "
                     + "VALUES ('deposit', '{}', ?, 'RECEIVED')")) {
            ps.setString(1, wagerCode);
            ps.executeUpdate();
        }

        try {
            // Helper must now report the row.
            assertTrue("hasDepositRowForWager must observe the seeded row",
                    GscEventLogger.hasDepositRowForWager(wagerCode));

            // Diagnostic helper must surface state + receive time for the WARN log.
            GscEventLogger.DepositRowInfo info =
                    GscEventLogger.findDepositRowForWager(wagerCode);
            assertTrue("DepositRowInfo must be present", info != null);
            assertEquals("RECEIVED", info.processingStatus);
            assertTrue("received_at must be populated by the DB DEFAULT",
                    info.receivedAt != null);

            // The reconciler's guard depends on this lookup. If it returns
            // true (as we just asserted), the guard runs `continue` — the
            // credit path is never reached. There is no observable side
            // effect to assert against here without a Mongo seed + GSC stub
            // pair, so this test focuses on the load-bearing pre-condition;
            // see testOutcomeToString_includesSkippedDepositRow for the
            // counter-surfacing contract, and the smoke-test doc for the
            // full end-to-end with a stubbed GscWagerClient.
        } finally {
            try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
                 PreparedStatement ps = conn.prepareStatement(
                         "DELETE FROM vinplay.gsc_event_log WHERE gsc_wager_code = ?")) {
                ps.setString(1, wagerCode);
                ps.executeUpdate();
            }
        }
    }

    /**
     * Verifies the lookup also works for a COMPLETED row, not just RECEIVED —
     * the guard is intentionally state-agnostic so that a successful deposit
     * + an in-flight reconcile scan also dedups correctly. Without this, a
     * race where the deposit completes between Mongo scan and
     * {@code MoneyGateway.creditUser} would still double-pay.
     */
    @Test
    public void testReconcile_skipsWhenDepositRowCompleted() throws Exception {
        Assume.assumeFalse(
                "test.mysql.password or MYSQL_PASSWORD must be set. Skipping DB-bound test.",
                bootstrapSkipped);

        String wagerCode = TEST_WAGER_PREFIX + "completed_001";

        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "DELETE FROM vinplay.gsc_event_log WHERE gsc_wager_code = ?")) {
            ps.setString(1, wagerCode);
            ps.executeUpdate();
        }

        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "INSERT INTO vinplay.gsc_event_log "
                     + "(gsc_endpoint, raw_payload, gsc_wager_code, processing_status) "
                     + "VALUES ('deposit', '{}', ?, 'COMPLETED')")) {
            ps.setString(1, wagerCode);
            ps.executeUpdate();
        }

        try {
            assertTrue("hasDepositRowForWager must return true for COMPLETED rows",
                    GscEventLogger.hasDepositRowForWager(wagerCode));
            GscEventLogger.DepositRowInfo info =
                    GscEventLogger.findDepositRowForWager(wagerCode);
            assertTrue(info != null);
            assertEquals("COMPLETED", info.processingStatus);
        } finally {
            try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
                 PreparedStatement ps = conn.prepareStatement(
                         "DELETE FROM vinplay.gsc_event_log WHERE gsc_wager_code = ?")) {
                ps.setString(1, wagerCode);
                ps.executeUpdate();
            }
        }
    }

    /**
     * A different endpoint's row must NOT match the deposit-only guard.
     * If a {@code withdraw} row for the wager existed but no {@code deposit}
     * row, the reconciler should pay (the withdraw is the BET, by design
     * the deposit/settle is what may have crashed). Confirms the SQL
     * filter is endpoint-strict.
     */
    @Test
    public void testHasDepositRowForWager_ignoresWithdrawEndpoint() throws Exception {
        Assume.assumeFalse(
                "test.mysql.password or MYSQL_PASSWORD must be set. Skipping DB-bound test.",
                bootstrapSkipped);

        String wagerCode = TEST_WAGER_PREFIX + "withdraw_only_001";

        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "DELETE FROM vinplay.gsc_event_log WHERE gsc_wager_code = ?")) {
            ps.setString(1, wagerCode);
            ps.executeUpdate();
        }

        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "INSERT INTO vinplay.gsc_event_log "
                     + "(gsc_endpoint, raw_payload, gsc_wager_code, processing_status) "
                     + "VALUES ('withdraw', '{}', ?, 'COMPLETED')")) {
            ps.setString(1, wagerCode);
            ps.executeUpdate();
        }

        try {
            assertFalse("hasDepositRowForWager must IGNORE withdraw rows",
                    GscEventLogger.hasDepositRowForWager(wagerCode));
        } finally {
            try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
                 PreparedStatement ps = conn.prepareStatement(
                         "DELETE FROM vinplay.gsc_event_log WHERE gsc_wager_code = ?")) {
                ps.setString(1, wagerCode);
                ps.executeUpdate();
            }
        }
    }
}
