package com.vinplay.dal.service;

import com.vinplay.vbee.common.config.VBeePath;
import com.vinplay.vbee.common.pools.ConnectionPool;
import org.junit.AfterClass;
import org.junit.Assume;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;

import static org.junit.Assert.*;

/**
 * Integration tests for {@link VipPointsService}.
 *
 * <p>Verifies:
 * <ol>
 *   <li>{@link VipPointsService#addPoints} writes one vip_point_log row
 *       per call and bumps {@code vip_points.current_points} +
 *       {@code lifetime_points} correctly.</li>
 *   <li>Re-posting the same {@code (reason, sourceTxId)} pair is a
 *       no-op (idempotency).</li>
 *   <li>Negative delta decrements {@code current} but leaves
 *       {@code lifetime} unchanged (monotonic invariant).</li>
 *   <li>{@link VipPointsService#getCurrent} / {@link VipPointsService#getLifetime}
 *       reflect the committed state.</li>
 * </ol>
 *
 * <p><b>Prerequisite:</b> sunwinkr-mysql Docker container running on
 * 127.0.0.1:3306 with the Phase 6 migration
 * ({@code 20260601_phase6_vip_points_table.sql}) applied.  The test user
 * {@link #TEST_USER_ID} must exist in {@code users}.
 *
 * <p><b>Password injection:</b> supply via {@code -Dtest.mysql.password=&lt;pw&gt;}
 * or the {@code MYSQL_PASSWORD} env var.  When neither is set, tests are
 * skipped (not failed) via {@link Assume}.
 *
 * <pre>
 *   ./gradlew :VinPlayDAL:test --tests VipPointsServiceTest \
 *      -Dtest.mysql.password=$(grep MYSQL_PASSWORD /path/to/.env | cut -d= -f2)
 * </pre>
 */
public class VipPointsServiceTest {

    /** Pre-existing user.  Same id used by MoneyGatewayDualWriteTest. */
    private static final long TEST_USER_ID = 5107L;

    /** Prefix for all source_tx_ids created by this suite. */
    private static final String TX_PREFIX = "test_vps_";

    private static volatile boolean bootstrapSkipped = false;

    // -----------------------------------------------------------------
    // Bootstrap (mirrors MoneyGatewayDualWriteTest pattern)
    // -----------------------------------------------------------------

    @BeforeClass
    public static void bootstrapPool() throws Exception {
        String pw = System.getProperty("test.mysql.password");
        if (pw == null || pw.isEmpty()) pw = System.getenv("MYSQL_PASSWORD");
        if (pw == null || pw.isEmpty()) {
            bootstrapSkipped = true;
            System.out.println("VipPointsServiceTest: password not supplied; tests will be skipped");
            return;
        }

        URL propsUrl = VipPointsServiceTest.class
                .getClassLoader()
                .getResource("config/db_pool.properties");
        String resourcesDir = propsUrl.getPath().replace("config/db_pool.properties", "");
        VBeePath.basePath = resourcesDir;

        Properties props = new Properties();
        try (InputStream is = propsUrl.openStream()) { props.load(is); }
        final String PLACEHOLDER = "__INJECT_AT_TEST_TIME__";
        if (PLACEHOLDER.equals(props.getProperty("mysqlpoolname.password", ""))) {
            props.setProperty("mysqlpoolname.password", pw);
        }
        java.io.File propsFile = new java.io.File(propsUrl.toURI());
        try (java.io.FileOutputStream fos = new java.io.FileOutputStream(propsFile)) {
            props.store(fos, "Auto-generated by VipPointsServiceTest — password injected at test time");
        }

        ConnectionPool.getInstance();
    }

    @AfterClass
    public static void cleanUp() {
        if (bootstrapSkipped) return;
        try {
            URL propsUrl = VipPointsServiceTest.class
                    .getClassLoader()
                    .getResource("config/db_pool.properties");
            if (propsUrl != null) {
                Properties props = new Properties();
                try (InputStream is = propsUrl.openStream()) { props.load(is); }
                props.setProperty("mysqlpoolname.password", "__INJECT_AT_TEST_TIME__");
                java.io.File propsFile = new java.io.File(propsUrl.toURI());
                try (java.io.FileOutputStream fos = new java.io.FileOutputStream(propsFile)) {
                    props.store(fos, "Integration-test DB pool — placeholder restored");
                }
            }
        } catch (Exception ignored) {}

        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname")) {
            try (PreparedStatement ps = conn.prepareStatement(
                    "DELETE FROM vinplay.vip_point_log WHERE source_tx_id LIKE '" + TX_PREFIX + "%'")) {
                int n = ps.executeUpdate();
                System.out.println("VipPointsServiceTest cleanup: deleted " + n + " vip_point_log rows");
            }
            // Roll back the counter mutations the suite made so subsequent
            // runs see a clean starting balance.
            try (PreparedStatement ps = conn.prepareStatement(
                    "DELETE FROM vinplay.vip_points WHERE user_id = ?")) {
                ps.setLong(1, TEST_USER_ID);
                ps.executeUpdate();
            }
        } catch (Exception e) {
            System.err.println("VipPointsServiceTest cleanup (non-fatal): " + e.getMessage());
        }
    }

    @Before
    public void skipIfNoPassword() {
        Assume.assumeFalse(
                "test.mysql.password or MYSQL_PASSWORD must be set",
                bootstrapSkipped);
        // Ensure each test starts from a known zero state.
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "DELETE FROM vinplay.vip_points WHERE user_id = ?")) {
            ps.setLong(1, TEST_USER_ID);
            ps.executeUpdate();
        } catch (Exception ignored) {}
    }

    // -----------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------

    private int countLogRows(String txId) throws Exception {
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT COUNT(*) FROM vinplay.vip_point_log WHERE source_tx_id = ?")) {
            ps.setString(1, txId);
            try (ResultSet rs = ps.executeQuery()) { rs.next(); return rs.getInt(1); }
        }
    }

    private long readCurrent(long userId) throws Exception {
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT current_points FROM vinplay.vip_points WHERE user_id = ?")) {
            ps.setLong(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? rs.getLong("current_points") : 0L;
            }
        }
    }

    private long readLifetime(long userId) throws Exception {
        try (Connection conn = ConnectionPool.getInstance().getConnection("mysqlpoolname");
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT lifetime_points FROM vinplay.vip_points WHERE user_id = ?")) {
            ps.setLong(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? rs.getLong("lifetime_points") : 0L;
            }
        }
    }

    // -----------------------------------------------------------------
    // Tests
    // -----------------------------------------------------------------

    /** Positive delta bumps both current + lifetime; one log row. */
    @Test
    public void testAddPoints_PositiveBumpsBothCounters() throws Exception {
        String tx = TX_PREFIX + "pos_001";
        boolean ok = VipPointsService.addPoints(
                TEST_USER_ID, 100L, VipPointsService.SOURCE_GAME_WIN, tx);
        assertTrue("addPoints should succeed", ok);
        assertEquals("one log row written", 1, countLogRows(tx));
        assertEquals("current_points bumped", 100L, readCurrent(TEST_USER_ID));
        assertEquals("lifetime_points bumped", 100L, readLifetime(TEST_USER_ID));
        assertEquals("getCurrent matches DB", 100L, VipPointsService.getCurrent(TEST_USER_ID));
        assertEquals("getLifetime matches DB", 100L, VipPointsService.getLifetime(TEST_USER_ID));
    }

    /** Lifetime accumulates across multiple positive deltas. */
    @Test
    public void testAddPoints_LifetimeAccumulation() throws Exception {
        VipPointsService.addPoints(TEST_USER_ID, 50L,
                VipPointsService.SOURCE_GAME_WIN, TX_PREFIX + "acc_001");
        VipPointsService.addPoints(TEST_USER_ID, 75L,
                VipPointsService.SOURCE_GAME_WIN, TX_PREFIX + "acc_002");
        VipPointsService.addPoints(TEST_USER_ID, 25L,
                VipPointsService.SOURCE_GAME_WIN, TX_PREFIX + "acc_003");

        assertEquals("current_points sums positive deltas", 150L, readCurrent(TEST_USER_ID));
        assertEquals("lifetime_points sums positive deltas", 150L, readLifetime(TEST_USER_ID));
    }

    /**
     * Re-posting the same (reason, sourceTxId) pair must NOT mutate
     * the counters and MUST return true (idempotent success).
     */
    @Test
    public void testAddPoints_IdempotencyOnDuplicateTxId() throws Exception {
        String tx = TX_PREFIX + "idem_001";
        assertTrue(VipPointsService.addPoints(
                TEST_USER_ID, 200L, VipPointsService.SOURCE_GAME_WIN, tx));
        long currAfterFirst = readCurrent(TEST_USER_ID);
        long lifeAfterFirst = readLifetime(TEST_USER_ID);

        // Re-post.  Same (reason, sourceTxId) — must be a no-op.
        assertTrue("idempotent retry returns true",
                VipPointsService.addPoints(TEST_USER_ID, 200L,
                        VipPointsService.SOURCE_GAME_WIN, tx));
        assertEquals("exactly one log row for the duplicate tx",
                1, countLogRows(tx));
        assertEquals("current unchanged after duplicate",
                currAfterFirst, readCurrent(TEST_USER_ID));
        assertEquals("lifetime unchanged after duplicate",
                lifeAfterFirst, readLifetime(TEST_USER_ID));
    }

    /**
     * Negative delta decrements current_points but leaves lifetime
     * unchanged (monotonic invariant per RFC §Phase 6).
     */
    @Test
    public void testAddPoints_NegativeKeepsLifetimeMonotonic() throws Exception {
        VipPointsService.addPoints(TEST_USER_ID, 500L,
                VipPointsService.SOURCE_GAME_WIN, TX_PREFIX + "mon_seed");
        long lifeBefore = readLifetime(TEST_USER_ID);

        assertTrue(VipPointsService.addPoints(TEST_USER_ID, -150L,
                VipPointsService.SOURCE_VIP_CASHOUT, TX_PREFIX + "mon_redeem"));

        assertEquals("current decremented", 350L, readCurrent(TEST_USER_ID));
        assertEquals("lifetime unchanged on negative delta",
                lifeBefore, readLifetime(TEST_USER_ID));
    }

    /** A different (reason, sourceTxId) is NOT idempotent with the first. */
    @Test
    public void testAddPoints_DifferentReasonSameTxIsNotDuplicate() throws Exception {
        String tx = TX_PREFIX + "reason_split";
        assertTrue(VipPointsService.addPoints(TEST_USER_ID, 30L,
                VipPointsService.SOURCE_GAME_WIN, tx));
        assertTrue(VipPointsService.addPoints(TEST_USER_ID, 30L,
                VipPointsService.SOURCE_HOAN_TRA, tx));
        assertEquals("both reasons recorded", 60L, readCurrent(TEST_USER_ID));
    }
}
