#vinplay
name=mysqlpoolname
drivers=com.mysql.jdbc.Driver
mysqlpoolname.url=jdbc:mysql://mysql:3306/vinplay?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&connectionTimeZone=Asia/Seoul&forceConnectionTimeZoneToSession=true&connectTimeout=5000&socketTimeout=30000
mysqlpoolname.user=sunwinkr_user
mysqlpoolname.password=hpDVmvyeThwderjl2zpnHD1wq2qdWe3i
mysqlpoolname.minpool=10
mysqlpoolname.maxpool=50
mysqlpoolname.maxsize=60
mysqlpoolname.idleTimeout=900
#vinplay_minigame
name=mysqlpool_minigame
drivers=com.mysql.jdbc.Driver
mysqlpool_minigame.url=jdbc:mysql://mysql:3306/vinplay_minigame?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&connectionTimeZone=Asia/Seoul&forceConnectionTimeZoneToSession=true&connectTimeout=5000&socketTimeout=30000
mysqlpool_minigame.user=sunwinkr_user
mysqlpool_minigame.password=hpDVmvyeThwderjl2zpnHD1wq2qdWe3i
mysqlpool_minigame.minpool=10
mysqlpool_minigame.maxpool=50
mysqlpool_minigame.maxsize=60
mysqlpool_minigame.idleTimeout=900
#vinplay_minigame_admin
name=mysqlpool_admin
drivers=com.mysql.jdbc.Driver
mysqlpool_admin.url=jdbc:mysql://mysql:3306/vinplay_admin?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&connectionTimeZone=Asia/Seoul&forceConnectionTimeZoneToSession=true&connectTimeout=5000&socketTimeout=30000
mysqlpool_admin.user=sunwinkr_user
mysqlpool_admin.password=hpDVmvyeThwderjl2zpnHD1wq2qdWe3i
mysqlpool_admin.minpool=0
mysqlpool_admin.maxpool=5
mysqlpool_admin.maxsize=10
mysqlpool_admin.idleTimeout=900
#game bai
name=mysqlpool_gamebai
drivers=com.mysql.jdbc.Driver
mysqlpool_gamebai.url=jdbc:mysql://mysql:3306/vinplay_gamebai?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&connectionTimeZone=Asia/Seoul&forceConnectionTimeZoneToSession=true&connectTimeout=5000&socketTimeout=30000
mysqlpool_gamebai.user=sunwinkr_user
mysqlpool_gamebai.password=hpDVmvyeThwderjl2zpnHD1wq2qdWe3i
mysqlpool_gamebai.minpool=0
mysqlpool_gamebai.maxpool=5
mysqlpool_gamebai.maxsize=10
mysqlpool_gamebai.idleTimeout=900

