package com.sunwinkr.minigame.api.scheduler;

import com.sunwinkr.minigame.engine.snapshot.TaiXiuSnapshot;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Singleton-managed live round state for the standalone TaiXiu scheduler
 * (SUN-1341 E1). Holds volatile round metadata and a ConcurrentHashMap of
 * pending bets — no Hazelcast, no BitZero shared memory.
 *
 * <h3>Threading model</h3>
 * <ul>
 *   <li>Round lifecycle fields ({@link #roundId}, {@link #bettingState},
 *       {@link #safeBetExpiresAt}) are {@code volatile} so HTTP threads
 *       reading state or accepting bets see happens-before writes from the
 *       scheduler thread.</li>
 *   <li>Bet storage is a {@link ConcurrentHashMap} — bet acceptance and
 *       settle snapshot both take a lock-free view.</li>
 * </ul>
 *
 * <p>Plan SUN-1341 §E1.
 */
@Component
public class TaiXiuRoundState {

    private static final Logger LOG = LoggerFactory.getLogger(TaiXiuRoundState.class);

    /** Monotonically increasing round id. */
    private final AtomicLong roundIdCounter = new AtomicLong(0L);

    /** True iff bets are currently accepted. */
    private volatile boolean bettingState = false;

    /** Absolute epoch-ms after which bets are rejected. 0 = no active round. */
    private volatile long safeBetExpiresAt = 0L;

    /** Dice values for the current round (null = not yet revealed). */
    private volatile short[] revealedDice = null;

    /** Wall-clock start of the current round (ms). */
    private volatile long roundStartMs = 0L;

    /**
     * Per-round bet list. Key = autogenerated bet id (String); value = PendingBet.
     * Cleared atomically at the start of each new round.
     */
    private final ConcurrentHashMap<String, PendingBet> pendingBets = new ConcurrentHashMap<>();

    /** Auto-increment for pending bet keys within a round. */
    private final AtomicLong betSeq = new AtomicLong(0L);

    // -----------------------------------------------------------------------
    // Round lifecycle mutations (called by TaiXiuRoundScheduler only)
    // -----------------------------------------------------------------------

    /**
     * Open a new round. Increments {@link #roundIdCounter}, clears bets and
     * dice, flips betting open.
     *
     * @param bettingWindowMs  duration in ms the bet window stays open
     * @return the new round id
     */
    public long openNewRound(long bettingWindowMs) {
        long newRoundId = roundIdCounter.incrementAndGet();
        // Clear previous round state
        pendingBets.clear();
        betSeq.set(0L);
        revealedDice = null;
        roundStartMs = System.currentTimeMillis();
        safeBetExpiresAt = roundStartMs + bettingWindowMs;
        bettingState = true;
        LOG.info("TaiXiuRoundState.openNewRound: roundId={} bettingOpen until epoch={}",
                 newRoundId, safeBetExpiresAt);
        return newRoundId;
    }

    /**
     * Close the bet window — flip {@link #bettingState} false, clear
     * {@link #safeBetExpiresAt}.
     */
    public void lockBetting() {
        bettingState = false;
        safeBetExpiresAt = 0L;
        LOG.info("TaiXiuRoundState.lockBetting: roundId={}", roundIdCounter.get());
    }

    /**
     * Publish revealed dice for this round.
     *
     * @param dice three-element short array [d1, d2, d3]
     */
    public void revealDice(short[] dice) {
        if (dice == null || dice.length < 3) {
            throw new IllegalArgumentException("dice must be short[3]");
        }
        this.revealedDice = new short[]{dice[0], dice[1], dice[2]};
        LOG.info("TaiXiuRoundState.revealDice: roundId={} dice=[{},{},{}] sum={}",
                 roundIdCounter.get(), dice[0], dice[1], dice[2],
                 dice[0] + dice[1] + dice[2]);
    }

    // -----------------------------------------------------------------------
    // Bet registration (called by HTTP bet path)
    // -----------------------------------------------------------------------

    /**
     * Register a new bet. The caller must have already validated timing
     * (now &lt; safeBetExpiresAt) and debited the wallet.
     *
     * @return a unique bet key for this round
     */
    public String registerBet(PendingBet bet) {
        String key = roundIdCounter.get() + "-" + betSeq.incrementAndGet();
        pendingBets.put(key, bet);
        return key;
    }

    /**
     * Drain all pending bets as an immutable snapshot for settle.
     * Does NOT clear the map — the scheduler calls this before clearing
     * on {@link #openNewRound}.
     */
    public List<PendingBet> drainBets() {
        return Collections.unmodifiableList(new ArrayList<>(pendingBets.values()));
    }

    // -----------------------------------------------------------------------
    // Read-only accessors
    // -----------------------------------------------------------------------

    public long getRoundId() {
        return roundIdCounter.get();
    }

    public boolean isBettingOpen() {
        return bettingState && System.currentTimeMillis() < safeBetExpiresAt;
    }

    public long getSafeBetExpiresAt() {
        return safeBetExpiresAt;
    }

    /** Dice for the current round; null if not yet revealed. */
    public short[] getRevealedDice() {
        return revealedDice;
    }

    public long getRoundStartMs() {
        return roundStartMs;
    }

    /**
     * Build a {@link TaiXiuSnapshot} from live state. This is called by
     * {@link com.sunwinkr.minigame.api.controller.TaiXiuController} when
     * the standalone scheduler is enabled.
     *
     * @param nickname  requesting user (per-user pot fields TBD)
     */
    public TaiXiuSnapshot toSnapshot(String nickname) {
        TaiXiuSnapshot s = new TaiXiuSnapshot();
        long rid = roundIdCounter.get();
        short[] dice = revealedDice;

        s.referenceId     = rid;
        s.roundId         = rid;
        s.bettingState    = isBettingOpen();
        s.bettingClosesAt = safeBetExpiresAt;
        s.remainTime      = computeRemainTime();

        if (dice != null && dice.length >= 3) {
            s.dice1 = dice[0];
            s.dice2 = dice[1];
            s.dice3 = dice[2];
            int sum = dice[0] + dice[1] + dice[2];
            // TAI wins when sum ∈ [11..17], XIU wins when sum ∈ [4..10].
            // Triple (sum=3 or sum=18) is treated as XIU per legacy rule.
            s.result = (sum >= 11) ? (short) 1 : (short) 0;
        } else {
            s.dice1 = 0;
            s.dice2 = 0;
            s.dice3 = 0;
            s.result = (short) -1; // pre-reveal
        }
        return s;
    }

    /** Remaining seconds in the current round phase (approx). */
    private short computeRemainTime() {
        long start = roundStartMs;
        if (start == 0L) {
            return (short) 0;
        }
        long elapsed = (System.currentTimeMillis() - start) / 1000L;
        long remain = 60L - elapsed;
        if (remain < 0) {
            remain = 0;
        }
        return (short) Math.min(remain, Short.MAX_VALUE);
    }

    // -----------------------------------------------------------------------
    // Inner type — pending bet record
    // -----------------------------------------------------------------------

    /**
     * Immutable record of a bet accepted during the open window.
     */
    public static final class PendingBet {
        public final String nickname;
        public final long   roundId;
        public final long   betValue;
        public final short  betSide;     // 1=TAI, 0=XIU
        public final short  moneyType;   // 1=VIN, 0=XU
        public final long   perBetTxId;
        public final long   acceptedAtMs;

        public PendingBet(String nickname,
                          long   roundId,
                          long   betValue,
                          short  betSide,
                          short  moneyType,
                          long   perBetTxId,
                          long   acceptedAtMs) {
            this.nickname      = nickname;
            this.roundId       = roundId;
            this.betValue      = betValue;
            this.betSide       = betSide;
            this.moneyType     = moneyType;
            this.perBetTxId    = perBetTxId;
            this.acceptedAtMs  = acceptedAtMs;
        }
    }
}
